### ISSUE TITLE
Circuit name

### ISSUE THREAD

**Issue by luci84tm** [CrazYoshi/ebusdpy#1]
Hi there, 

What do I have to configure as circuit in home assistant?

ebusd:
host: 127.0.0.1
circuit: '700'

https://www.home-assistant.io/components/ebusd/

I tried with bai, but that seems to give me some exception:

2019-03-08 15:47:23 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up platform ebusd
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 400, in wait_for
    return fut.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/ebusd/sensor.py", line 30, in setup_platform
    ebusd_api, discovery_info['sensor_types'][condition], name))
KeyError: 'WaterPressure'

**Comment by CrazYoshi** [comment]
circuit is the one you see using ebusctl info command:
`pi@homedaemon:~/ebusdpy/ebusdpy$ ebusctl info
version: ebusd 3.2.v3.2-12-g45b9bad
update check: version 3.3 available, broadcast.csv: different version available, vaillant/15.700.csv: different version available, vaillant/bai.308523.inc: different version available, vaillant/broadcast.csv: different version available, vaillant/errors.inc: different version available, vaillant/hcmode.inc: different version available
signal: acquired
symbol rate: 23
max symbol rate: 159
min arbitration micros: 15
max arbitration micros: 337
min symbol latency: 0
max symbol latency: 59
reconnects: 0
masters: 3
messages: 611
conditional: 3
poll: 0
update: 9
address 03: master #11
address 08: slave #11, scanned "MF=Vaillant;ID=BAI00;SW=0603;HW=1303", loaded "vaillant/bai.308523.inc", "vaillant/08.bai.csv"
address 10: master #2
address 15: slave #2, scanned "MF=Vaillant;ID=70000;SW=0110;HW=2103", loaded "vaillant/15.700.csv"
address 31: master #8, ebusd
address 36: slave #8, ebusd
`
Usually it is the one before .csv file extension

**Comment by luci84tm** [comment]
So you mean in my case: bai or 350 ?


pi@raspberrypi:~ $ ebusctl info
version: ebusd 3.3.v3.3
update check: revision v3.3-4-g212b22d available, broadcast.csv: different version available, vaillant/15.350.csv: different version available, vaillant/bai.308523.inc: different version available, vaillant/broadcast.csv: different version available, vaillant/errors.inc: different version available, vaillant/hcmode.inc: different version available
signal: acquired
symbol rate: 16
max symbol rate: 95
min arbitration micros: 2098
max arbitration micros: 3346
min symbol latency: 4
max symbol latency: 6
reconnects: 0
masters: 3
messages: 410
conditional: 7
poll: 0
update: 9
address 03: master #11
address 08: slave #11, scanned "MF=Vaillant;ID=BAI00;SW=0518;HW=7401", loaded "vaillant/bai.308523.inc" ([HW=7401]), "vaillant/08.bai.csv"
address 10: master #2
address 15: slave #2, scanned "MF=Vaillant;ID=35000;SW=0114;HW=7102", loaded "vaillant/15.350.csv"
address 31: master #8, ebusd
address 36: slave #8, ebusd

**Comment by luci84tm** [comment]
Would it be possible to add support for additional circuit in the const.py ?

if I run the following command: 
`pi@rp3:~ $  ebusctl find -r -F circuit,name,comment
350,ActualPumpPower,
350,ActualRoomTempDesired,Aktueller Raumsollwert[°C]
350,ActualTempDesired,
350,ActualWeekday,
350,BypassValve,
350,C1C2State,
350,CirPump,
350,ClockSwitchSummerWinterDone,
350,CMResetCnt,
350,CollPumpHRuntime,
350,COMErrorCnt,
350,ComfTempDesired,
350,ComfTempEnabled,
350,ControlMode,
350,Date,
350,DcfDaten,
350,DisableAutoSync,
350,eBUSCRC,
350,eBUSFifoDiffCntMax,
350,EDControlEnabled,
350,EEpromMaxInkonsCnt,
350,ElectronicCartridge,
350,FillmodeStartTime,
350,FlowTempMin,
350,FrostProtectDelay,
350,HeatingCurve,
350,HwcState,
350,HwcTempDesired,
350,HydraulicMixer,
350,HydraulicScheme,
350,IsInFloorPavingDrying,
350,IsInHoliday,
350,IsInParty,
350,IsInQuickVeto,
350,IsInSavingsFunction,
350,IsInSingleHwcLoadingMode,
350,IsInTeleSwitch,
350,LegioProtectionEnabled,
350,LegioProtectionState,
350,LegioPump,
350,LoadingDelayEnabled,
350,LVResetCnt,
350,NumCollPanels,
350,OffDiff,
350,OffsetDesTemp,
350,ONDiff,
350,ONMAXDiff,
350,ONMINDiff,
350,OperatingMode,
350,OperatingModeHwc,
350,OperatingmodeStartTime,
350,OtShutdownLimit,
350,OutsideTemp,Außentemperatur [°C]
350,OutsideTempOffset,
350,POCResetCnt,
350,PrevOperatingMode,
350,PumpPower,
350,QuickVetoTemp,
350,ReducedNightTemp,
350,ResetOperatingTimes,
350,ResetYield,
350,RestoreOpModeAfterHoliday,
350,resvdColl1Sensor,
350,resvdColl2Sensor,
350,resvdCollPump1,
350,resvdCollPump2,
350,resvdStorage1Sensor,
350,resvdStorage2Sensor,
350,resvdStorage3Sensor,
350,ROCRoomSet,
350,RoomTemp,Aktuelle Raumtemperatur
350,RoomTempOffset,
350,RoomTempOffsetSelfWarming,
350,RoomTempSwitchOn,
350,RTCAdjustment,
350,SavingsFunctionTime,
350,SolFlowRate,Volumenstrom Solarkreis [l/h]
350,SolHwcMaxLoadTemp,
350,SolPumpBlockingTime,
350,StackeBUSTaskMax,
350,StackLifeCheckTaskMax,
350,StackMainTaskMax,
350,StartCircuitAeration,
350,StateOfRoomCon,
350,StatusDcf,
350,SwitchOffParty,
350,TeleSwOperatingMode,
350,Time,
350,TimeWindows,
350,UV1State,
350,Variant,
350,VariantDKRefreshCnt,
350,WDResetCnt,
350,WeekDayProgSwitch,
350,YearCalendarActive,
350,Yield,
350,YieldSensor,
350,ZweipunktAnalogSlct,
bai,AccessoriesOne,d.27 Zubehörrelais 1
bai,AccessoriesTwo,d.28 Zubehörrelais 2
bai,ACRoomthermostat,d.08 Raumthermostat
bai,APCComStatus,d.92 APC_ComStatus_DK
bai,APCLegioProtection,d.74 APC_LegioProtection
bai,averageIgnitiontime,d.64 Mittlere Zündzeit
bai,BlockTimeHcMax,d.02 Maximale Brennersperrzeit
bai,BoilerType,BoilerType_DK
bai,ChangesDSN,Anzhl der DSN Änderungen
bai,CirPump,d.13 Zirkulationspumpe
bai,CounterStartattempts1,d.68 Zündfehler 1. Versuch
bai,CounterStartattempts2,d.69 Zündfehler 2. Versuch
bai,CounterStartAttempts3,Zündfehler 3. Versuch
bai,CounterStartAttempts4,Zündfehler 4. Versuch
bai,currenterror,Aktuelle Fehler
bai,DateTime,Datum Uhrzeit
bai,dcfState,d.91 DCF Status
bai,DCFTimeDate,DCF Datum/Uhrzeit
bai,DCRoomthermostat,d.16 Raumthermostat
bai,DeactivationsIFC,d.61 Anzahl Zündfehler
bai,DeactivationsTemplimiter,d.60 STB Abschaltungen
bai,DeltaFlowReturnMax,MaxDeltaFlowReturn_DK
bai,DisplayMode,DisplayMode_DK
bai,DSN,DSN
bai,DSNOffset,d.93 Gerätekennung
bai,DSNStart,DSN Startadresse
bai,EBusHeatcontrol,d.90 Digitaler Regler
bai,EbusSourceOn,eBUS Spannungsversorgung
bai,EbusVoltage,eBUS Spannung
bai,errorhistory,Fehlerhistorie
bai,expertlevel_ReturnTemp,Rücklauftemperatur
bai,ExternalFaultmessage,Ext. Störmeldung
bai,externalFlowTempDesired,ext. Vorlaufsollwert
bai,externalHwcSwitch,Wasserschalter
bai,ExternGasvalve,Ext. Gasventil
bai,ExtFlowTempDesiredMin,d.09 Min. ext. Vorlaufsollwert
bai,ExtStorageModulCon,VR65 angeschlossen
bai,extWP,d.11 ext. Heizungspumpe
bai,FanHours,Betriebsstunden Lüfter
bai,FanMaxSpeedOperation,Max. Lüfterdrehzahl
bai,FanMinSpeedOperation,Min. Lüfterdrehzahl
bai,FanPWMSum,Fan_PWM_Sum_DK
bai,FanPWMTest,Fan_PWM_Test_DK
bai,FanSpeed,d.34 Lüfteristdrehzahl
bai,FanSpeedOffsetMax,d.51 Offset max. Lüfterdrehzahl
bai,FanSpeedOffsetMin,d.50 Offet min. Lüfterdrehzahl
bai,FanStarts,FanCommunt_DK
bai,Flame,Flammensignal
bai,FlameSensingASIC,SD_Flame_Sensing_ASIC_DK
bai,FloorHeatingContact,Anlegethermostat
bai,FlowsetHcMax,d.71 Max. Vorlauftemp. Heizbetrieb
bai,FlowsetHwcMax,d.78 Max. Vorlauftemp. WW
bai,FlowSetPotmeter,Vorlaufsollwert Poti
bai,FlowTemp,d.40 Vorlauftemperatur
bai,FlowTempDesired,d.05 Vorlaufsolltemperatur
bai,FlowTempMax,Max. Vorlauftemperatur
bai,Fluegasvalve,Abgasklappe
bai,FluegasvalveOpen,Abgasklappe offen
bai,Gasvalve3UC,Gasventil 3
bai,Gasvalve,d.30 Gasventil
bai,GasvalveASICFeedback,Rückmeldung Gasventil
bai,GasvalveUC,Gasventil
bai,GasvalveUCFeedback,Rückmeldung Gasventil
bai,HcHours,d.80 Hz. Betriebsstunden
bai,HcPumpMode,d.18 Pumpenbetriebsart
bai,HcPumpStarts,CH_PumpCommunt_DK
bai,HcStarts,d.82 Schaltspiele Heizbetrieb
bai,HcUnderHundredStarts,HZ_UnderHundred_SwiActi_DK
bai,HeatingSwitch,d.23 Winterbetrieb
bai,HoursTillService,d.84 Stunden bis Wartung
bai,HwcDemand,d.22 WW Anforderung
bai,HwcHours,d.81 Betriebsstunden WW
bai,HwcImpellorSwitch,Brauchwasserzapfung
bai,HwcPostrunTime,d.72 WW Pumpnenachlaufzeit
bai,HwcSetPotmeter,WW Sollwert Potentiometer
bai,HwcStarts,d.83 Schaltspiele BW Betrieb
bai,HwcSwitch,Wasserschalter
bai,HwcTemp,d.03 WW Vorlaufsolltemp
bai,HwcTempDesired,d.06 Brauchwassersollwert
bai,HwcTempMax,d.20 Max. WW Temperatur
bai,HwcTypes,WW Typen
bai,HwcUnderHundredStarts,BW_UnderHundred_SwiActi_DK
bai,HwcWaterflow,d.36 Zapfmenge
bai,HwcWaterflowMax,Max. WW Vorlauftemp.
bai,Ignitor,Zünder
bai,InitialisationEEPROM,InitialisationEEPROM_DK
bai,IonisationVoltageLevel,d.44 Spannungspegel Ionisationssignal
bai,maintenancedata_HwcTempMax,Max. WW Temperatur
bai,maxIgnitiontime,d.65 Max. Zündzeit
bai,minIgnitiontime,Min. Zündzeit
bai,ModulationTempDesired,Modulationssollwert
bai,OutdoorstempSensor,d.47 Außentemperaturfühler
bai,OverflowCounter,Überlauf PM Zähler
bai,ParamToken,ParamToken_DK
bai,PartloadHcKW,d.00 Heizungsteillast
bai,PartloadHwcKW,d.77 Speicherteillast
bai,PartnumberBox,Partnumber_Box
bai,PositionValveSet,d.35 Position VUV
bai,PowerValue,Leistungsdaten
bai,PrAPSCounter,PrAPSCounter_DK
bai,PrAPSSum,PrAPSSum_DK
bai,PrEnergyCountHc1,PrEnergyCountCH1_DK
bai,PrEnergyCountHc2,PrEnergyCountCH2_DK
bai,PrEnergyCountHc3,PrEnergyCountCH3_DK
bai,PrEnergyCountHwc1,PrEnergyCountDHW1_DK
bai,PrEnergyCountHwc2,PrEnergyCountDHW2_DK
bai,PrEnergyCountHwc3,PrEnergyCountDHW3_DK
bai,PrEnergySumHc1,PrEnergySumCH1_DK
bai,PrEnergySumHc2,PrEnergySumCH2_DK
bai,PrEnergySumHc3,PrEnergySumCH3_DK
bai,PrEnergySumHwc1,PrEnergySumDHW1_DK
bai,PrEnergySumHwc2,PrEnergySumDHW2_DK
bai,PrEnergySumHwc3,PrEnergySumDHW3_DK
bai,ProductionByte,ProductionByte
bai,PrVortexFlowSensorValue,PrVortexFlowSensorValue_DK
bai,PumpHours,Betriebsstunden Pumpe
bai,PumpHwcFlowNumber,PumpDHWFlowNumber_DK
bai,PumpHwcFlowSum,PumpDHWFlowSum_DK
bai,RemainingBoilerblocktime,d.67 Verbleibende Brennersperrzeit
bai,ReturnRegulation,d.17 Rücklaufregelung
bai,ReturnTemp,d.41 Rücklauftemperatur
bai,ReturnTempMax,Max. Rücklauftemperatur
bai,SecondPumpMode,d.19 Betriebsart 2. Pumpe
bai,SerialNumber,SerialNumber
bai,SetFactoryValues,d.96 Werkseinstellungen
bai,SHEMaxDeltaHwcFlow,SHE_MaxDeltaFlowDHW_DK
bai,SHEMaxFlowTemp,Max. WW Vorlauftemp.
bai,SolPostHeat,d.58 Solarbetriebsart
bai,Statenumber,Statenumber_DK
bai,Status01,Vorlauftemperatur/Rücklauftemperatur/Aussentemperatur/WW Temperatur         /Speichertemperatur/Pumpenstatus
bai,Status02,Betriebsart/Maximaltemperatur/ReglerCurrentTEMP/Maximaltemperatur/R         eglerCurrentTemp
bai,Status16,Aussentemperatur
bai,Status,Status
bai,Storageloadpump,d.12 Speicherladepumpe
bai,StorageLoadPumpHours,TankLoadPumpOperationHours_DK
bai,StorageloadPumpStarts,TankloadPumpCommunt_DK
bai,StorageLoadTimeMax,d.75 Max. Speicherladezeit
bai,StoragereleaseClock,d.25 Speicherfreigabe
bai,StorageTemp,d.04 Speicheristtemp
bai,StorageTempDesired,d.07 Speichersolltemp
bai,StorageTempMax,Max. Speichertemp.
bai,TargetFanSpeed,d.33 Lüfter Solldrehzahl
bai,TargetFanSpeedOutput,Lüfter Solldrehzahl
bai,TempDiffBlock,TempDiffBlock_DK
bai,TempDiffFailure,TempDiffFailure_DK
bai,TempGradientFailure,Gradientenfehler
bai,Templimiter,Temperaturbegrenzer
bai,TemplimiterWithNTC,SD_STL_with_NTC
bai,TempMaxDiffExtTFT,MaxTempDiffExtTFT_DK
bai,Testbyte,Testbyte_DK
bai,TimerInputHc,Eingang Schaltuhr
bai,ValveMode,d.70 VUV Betriebsart
bai,ValveStarts,3WV Schaltspiele
bai,VolatileLockout,Verriegelnde Störabschaltungen
bai,VolatileLockoutIFCGV,SD_VolatileLockout_IFC_GV_DK
bai,VortexFlowSensor,VortexFlowSensor_DK
bai,WarmstartDemand,Warmstartanforderung
bai,WarmstartOffset,d.73 Warmstart Offset
bai,WaterHcFlowMax,MaxWaterFlowCH_DK
bai,WaterPressure,Wasserdruck
bai,WaterpressureBranchControlOff,Drucksprungerkennung ausschalten
bai,WaterpressureMeasureCounter,WaterpressureMeasureCounter_DK
bai,WaterpressureVariantSum,WaterpressureVariantSum_DK
bai,WP,d.10 Wasserpumpe
bai,WPPostrunTime,d.01 Pumpennachlaufzeit
bai,WPSecondStage,WP_SecondStage_DK
broadcast,id,Identifikation
general,valuerange,Register Wertebereich
memory,eeprom,EEPROM Daten lesen
memory,ram,RAM Daten lesen
scan,id,Scan ID
scan.08,,
scan.08,id,Scan ID
scan.15,,
scan.15,id,Scan ID`

I do have the circuit type 350 and allot more values for the "bai"

**Comment by CrazYoshi** [comment]
yes of course it is possible. You can create a fork and add make your own changes to const.py file
